name: Create Docs

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build Docs and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
        BUILD_SCRIPT: npm install -g redoc-cli && sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install apt-transport-https && sudo apt-get install dotnet-sdk-3.0 && dotnet build --configuration Debug && redoc-cli bundle -o docs/index.html docs/swagger.json
